Repository cse110-fa21-group33/cse110-fa21-group33, pull requests merged in 2021-12, with the labels that each got.

#105 Added more units and changed the jsons accordingly
  source/assets/components/RecipeUpload.js
  source/assets/jsons/Bun-Bo-Hue.json
  source/assets/jsons/Ghost-Pepper-Wings.json
  source/assets/jsons/Jalapeno-Garlic-Onion-Cheeseburger.json
  source/assets/jsons/Jjam-Bbong-Korean-Chinese-Spicy-Noodle.json
  source/assets/jsons/Sichuan-Style-Bird-Eye-Chili-Sauce.json
  source/assets/jsons/Southwest-Stuffed-Poblano-Pepper.json
  source/assets/jsons/Spicy-Shrimp-Pad-Thai.json
  source/assets/jsons/Spicy-Thai-Basil-Chicken-Pad-Krapow-Gai.json
  source/assets/jsons/Spicy-Touchdown-Chili.json
  source/assets/jsons/Tteokbokki-Spicy-Stir-Fried-Rice-Cakes.json
Labels: backend

#102 Made Slider display spice level and fixed some auto align stuff in nav Bar
  source/assets/components/RecipeCard.js
  source/assets/components/RecipeDisplay.js
  source/assets/images/fireGif1.gif
  source/assets/images/fireGif2.gif
  source/assets/images/fireGif3.gif
  source/assets/images/fireGif4.gif
  source/assets/images/fireGif5.gif
  source/assets/scripts/main.js
  source/assets/styles/style.css
  source/index.html
Labels: frontend

#107 Added images and colors for diff spice levels
  source/assets/images/background-1.png
  source/assets/images/background-2.png
  source/assets/images/background-3.png
  source/assets/images/background-4.png
  source/assets/images/background-5.png
  source/assets/styles/variables.css
Labels: frontend

#118 Fixed navigation from the search bar to show the recommended
  source/assets/scripts/main.js
Labels: frontend

#119 Added adr for challenge
  specs/adrs/113021-Challenge.md
Labels: notes, management

#133 Connected challenge to backend
  source/assets/components/RecipeDisplay.js
  source/assets/scripts/main.js
Labels: frontend, backend

#128 Add placeholder picture
  source/assets/components/RecipeCard.js
  source/assets/components/RecipeDisplay.js
  source/assets/components/RecipeUpload.js
Labels: frontend

#134 Fixed jsons
  source/assets/jsons/Carne-Asada-Tacos.json
  source/assets/jsons/Japanese-Curry-From-Scratch.json
  source/assets/jsons/Spicy-Chicken-Sandwich.json
  source/assets/jsons/Spicy-Habanero-Salsa.json
  source/assets/jsons/Zesty-Mango-Habanero-Hot-Sauce.json
  source/assets/scripts/database.js
Labels: bug

#138 Working delete buttons for the edit page
  source/assets/components/RecipeUpload.js
Labels: backend

#129 add confetti for the made this button, I add a jsconfetti.js in scripts and add a line of script source in index.html
  source/assets/components/RecipeDisplay.js
  source/assets/scripts/js-confetti.browser.js
  source/index.html
Labels: frontend

#143 Remove buttons work work now
  source/assets/components/RecipeUpload.js
Labels: backend

#150 Add user reaction functionality
  source/assets/components/RecipeDisplay.js
Labels: frontend, backend

#152 Added diffuser to the main page
  source/assets/styles/style.css
  source/index.html
Labels: frontend

#153 Update RecipeDisplay.js
  source/assets/components/RecipeDisplay.js
Labels: backend

#161 Added new image assets
  source/assets/images/chili-pepper-1.png
  source/assets/images/chili-pepper-2.png
  source/assets/images/tnt.png
Labels: frontend

#173 restored previous styling, added new challenge, fixed bug regarding recipe-card height consistency...
  source/assets/components/RecipeCard.js
  source/assets/components/RecipeDisplay.js
  source/assets/jsons/Cake-Mix-Chicken-Nuggets.json
  source/assets/jsons/Ghost-Pepper-Bison.json
  source/assets/jsons/Ghost-Pepper-Jelly.json
  source/assets/jsons/Ghost-Pepper-Queso.json
  source/assets/jsons/Ghost-Pepper-Wings.json
  source/assets/jsons/Korean-Chili-Pork-Lettuce-Cups.json
  source/assets/jsons/Pretzel-Crusted-Pickle-Chips.json
  source/assets/jsons/Reaper-Smoked-Breast.json
  source/assets/jsons/Sichuan-Lamb-Mushroom-Stirfry.json
  source/assets/jsons/challenges.json
  source/assets/scripts/database.js
  source/assets/styles/style.css
Labels: enhancement

#179 added dark mode styling
  source/assets/components/ChallengeBar.js
  source/assets/components/RecipeCard.js
  source/assets/components/RecipeDisplay.js
  source/assets/components/RecipeUpload.js
  source/assets/images/web-logo-blank.png
  source/assets/images/web-logo-dark.png
  source/assets/scripts/main.js
  source/assets/styles/style.css
  source/index.html
Labels: enhancement, on hold, frontend

#182 Updated wireframes and CHANGELOG
  CHANGELOG.md
  specs/interface/highfidelity/Recipe_Upload.png
Labels: management

#184 Finished most e2e tests
  __tests__/e2e.test.js
Labels: testing

#192 Fixed bug regarding the edit page breaking
  source/assets/components/RecipeUpload.js
Labels: bug

#193 Added changes to changenote and release and cleaned up repo
  CHANGELOG.md
  README.md
  release-notes.md
  source/.DS_Store
  source/assets/.DS_Store
  source/assets/components/ChallengeBar.js
  source/assets/components/RecipeCard.js
  source/assets/components/RecipeDisplay.js
  source/assets/components/RecipeUpload.js
  source/assets/styles/.DS_Store
  source/main/.DS_Store
Labels: documentation, management

#194 More cleanup and linting
  source/assets/components/RecipeCard.js
  source/assets/components/RecipeDisplay.js
  source/assets/components/RecipeUpload.js
  source/assets/images/.DS_Store
  source/assets/images/chili-pepper-1.png
  source/assets/images/chili-pepper-2.png
  source/assets/images/fireGif1.gif
  source/assets/images/fireGif2.gif
  source/assets/images/fireGif3.gif
  source/assets/images/fireGif4.gif
  source/assets/images/fireGif5.gif
  source/assets/images/v2.png
  source/assets/scripts/database.js
  source/assets/scripts/main.js
Labels: bug, documentation
