Repository cse110-fa21-group33/cse110-fa21-group33, pull requests merged in 2021-11, with the labels that each got.

#14 Added meeting notes for the week
  admin/meetings/110221-delegation.md
  admin/meetings/110421-coding.md
  admin/meetings/media/110221-chart.png
Labels: notes

#15 Added recipe page
  admin/meetings/110221-delegation.md
  source/assets/images/1-star.svg
  source/assets/images/placeholder.jpg
  source/assets/styles/recipe-styesheet.css
  source/recipe-page.html
Labels: enhancement

#16 moved pitch folder to specs
  specs/pitch/Exploding_Cats_Recipe_App.jpg
  specs/pitch/Exploding_Cats_Recipe_App_(2).jpg
  specs/pitch/Project Pitch.md
  specs/pitch/Screen_Shot_2021-10-28_at_9.19.11_PM.png
Labels: documentation

#17 Updated project pitch
  specs/brainstorm/wireframe-main-page.jpg
  specs/pitch/Exploding_Cats_Recipe_App.jpg
  specs/pitch/Project Pitch.md
  specs/pitch/database.drawio.png
Labels: documentation

#40 added recipe card to main and implemented fetch for some example recipes
  source/assets/scripts/main.js
  source/assets/scripts/recipeCard.js
  source/assets/styles/style.css
  source/index.html
Labels: enhancement

#43 Added database script
  .vscode/settings.json
  node_modules/.bin/acorn
  node_modules/.bin/eslint
  node_modules/.bin/js-yaml
  node_modules/.bin/json5
  node_modules/.bin/node-which
  node_modules/.bin/rimraf
  node_modules/.bin/semver
  node_modules/.package-lock.json
  node_modules/eslint-config-airbnb-base/node_modules/.bin/semver
  package-lock.json
  package.json
  source/assets/scripts/database.js
Labels: enhancement

#52 Added meeting notes and sprint review
  admin/meetings/111621-development.md
  admin/meetings/111621-sprint-1-review.md
  admin/meetings/111821-development.md
  admin/meetings/media/sprint-1/111621-1.png
  admin/meetings/media/sprint-1/111621-2.png
  admin/meetings/media/sprint-1/111621-3.png
  admin/meetings/media/sprint-1/111621-4.png
  admin/meetings/media/sprint-1/111621-5.png
Labels: documentation

#60 MVP upload complete
  editAndUpload/upload.html
  editAndUpload/upload.js
Labels: enhancement

#62 SPA for upload
  .vscode/settings.json
  source/assets/components/RecipeUpload.js
  source/assets/images/placeholder.png
  source/assets/scripts/main.js
  source/assets/styles/style.css
  source/index.html
Labels: enhancement

#81 attempting to fix click event for ios
  source/assets/components/RecipeCard.js
  source/assets/scripts/main.js
Labels: bug

#96 Added meeting notes from last week
  admin/meetings/112321-development.md
Labels: documentation

#97 Changes to the new logo and the favico
  source/assets/images/favico.png
  source/assets/images/placeholder.txt
  source/assets/images/web-logo.png
  source/assets/styles/style.css
  source/index.html
Labels: enhancement

#98 Added 5 more recipes to the initial database
  source/assets/jsons/Bun-Bo-Hue.json
  source/assets/jsons/Jjam-Bbong-Korean-Chinese-Spicy-Noodle.json
  source/assets/jsons/Spicy-Thai-Basil-Chicken-Pad-Krapow-Gai.json
  source/assets/jsons/Spicy-Touchdown-Chili.json
  source/assets/jsons/Tteokbokki-Spicy-Stir-Fried-Rice-Cakes.json
  source/assets/scripts/database.js
Labels: backend

#99 Added basic e2e test
  .babelrc
  .github/workflows/jest.yml
  .gitignore
  __tests__/e2e.test.js
  babel.config.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: testing
